### PR TITLE
Implemented the passing of client id to the rest of the application 

### PR DESCRIPTION
**Pull request by rodrigopavezi**
through a request attribute. If client id is null or empty it won't be passed.

@alexey-rise please review.

@tejohnso FYI.

Cheers!!

### CODE REVIEW

**Comment by alexey-rise** [comment]
@rodrigopavezi :+1: on the PR

On the filter in general: are you sure the log entry you are writing will be easy to parse from SQL in BQ?

**Comment by rodrigopavezi** [comment]
@alexey-rise yes, it will. I have successfully run the following query:

SELECT protoPayload.line.logMessage, protoPayload.line.time FROM [appengine_logs.appengine_googleapis_com_request_log_20150113] where protoPayload.line.logMessage like '%Monitoring:%' and protoPayload.line.logMessage like '%"api":"CORE"%' LIMIT 1000

What do you think?

Cheers!!

**Comment by alexey-rise** [comment]
@rodrigopavezi what about extracting `client Id` from the logs to be returned as part of the query response?

**Comment by rodrigopavezi** [comment]
@alexey-rise okay, the following is the log message from BQ

com.risevision.monitor.MonitoringFilter doFilter: Monitoring: clientId=292824132082.apps.googleusercontent.com, data:{"api":"CORE","resource":"/_ah/spi/com.risevision.core.api.v1.CoreAPIv1.getCompany","ipAddress":"177.92.48.83","hostname":"177.92.48.83","clientId":"292824132082.apps.googleusercontent.com"}

So, I was planning to get the substring after "data:" and use Gson.fromJson to create an object so the data can be managed.

Any thoughts?

Thanks!!

**Comment by alexey-rise** [comment]
@rodrigopavezi curious, do you need the path ("/_ah/spi/com.risevision.core.api.v1.CoreAPIv1.getCompany") for monitoring? Also, why is client ID repeated? 
You don't want to load more data than necessary from BQ because it will take more time/cost more money, right?

**Comment by rodrigopavezi** [comment]
@alexey-rise actually, at the moment it is implemented to send this data https://github.com/Rise-Vision/monitoring-filter/blob/master/src/main/java/com/risevision/monitoring/filter/Request.java? 

I thought that if we want to investigate an App, we would have enough information for that.

Do you suggest only sending API, Client Id, IP and Host name?

Thanks

**Comment by alexey-rise** [comment]
@rodrigopavezi isn't that data (or most of that data) already in the log entry (`protoPayload.resource`, `protoPayload.ip`, etc)?

I think you only need **API**, **client ID** and **IP** for the monitoring/blocking, unless I am missing something?

**Comment by rodrigopavezi** [comment]
@alexey-rise you are right. I will make the changes. It will only pass API and Client ID. We can get ip from protoPayload.ip Thanks

**Comment by rodrigopavezi** [comment]
@alexey-rise could you please have a look at the last commit? I have addressed the requirements we have been discussing here. So, filter now will be setup as the following on the web.xml

    <filter>
        <filter-name>MonitoringFilter</filter-name>
        <filter-class>com.risevision.monitoring.filter.MonitoringFilter</filter-class>
        <init-param>
            <param-name>service</param-name>
            <param-value>core</param-value>
            <param-name>apis</param-name>
            <param-value>CoreAPIv1,RiseAPIv2,TestAPIv0</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>MonitoringFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

Then the filter will get which is api making the call from the request URI: /_ah/spi/com.risevision.core.api.v0.RiseAPIv0.getApp

After the log message will be:  "Monitoring: data={"service": "core", "api": "RiseAPIv0", "clientId": "xxxxxxxxx"}"


What do you think?

Thanks a mill

**Comment by alexey-rise** [comment]
@rodrigopavezi what is the purpose of the `service` field? What does it do for the Monitoring?

**Comment by tejohnso** [comment]
What about the userid in addition to clientid as we discussed?

**Comment by rodrigopavezi** [comment]
@alexey-rise that is meaningful because we need to know which service the API is on e.g. core, storage, store. 

@tejohnso I am just looking at that, when you say userid do you mean the user email? 

thanks

**Comment by tejohnso** [comment]
Yeah, user email would be handy to have in all apps I would think.  Even if you don't add it here, I'll definitely be adding it for storage api logging.

**Comment by ByronDarlison** [comment]
Just to confirm, we have two fields in the core, username and email.
Username is the gmail account they use, email can be different. You guys
are talking about username right? Thanks

**Comment by tejohnso** [comment]
Yeah it would be the gmail account they used to authenticate with.

**Comment by ByronDarlison** [comment]
That is username. Thanks

**Comment by rodrigopavezi** [comment]
@tejohnso yeap. It agree with you.

Google already logs it as a message of the log messages for a request. 

18:08:05.707 com.google.api.server.spi.auth.AppEngineAuthUtils getCurrentUser: getCurrentUser: AccessToken; user=example@gmail.com

The problem will be to retrieve it from BQ as you have to have a request id. So, query looks like that: 

SELECT protoPayload.line.logMessage FROM [appengine_logs.appengine_googleapis_com_request_log_20150113] where protoPayload.requestId='NTRiNDZjMmYwMGZmMDM1M2I5NTViNTkyNDUwMDAxNzM3ZTcyNzY2MTYzNmY3MjY1MmQ3NDY1NzM3NDAwMDE3MzdlNzI3NjYxNjM2ZjcyNjUyZDc0NjU3Mzc0MmY2ZDZmNmU2OTc0NmY3MjY5NmU2NzAwMDEwMTM0' LIMIT 1000

Another option which I believe is better is to add the user email within log entry on the filter as we already have it from the clientId lookup through the token verification call.

https://github.com/Rise-Vision/monitoring-filter/blob/master/src/main/java/com/risevision/monitoring/filter/oauth/TokenInfo.java#L13

What you think?

Thanks

**Comment by alexey-rise** [comment]
@rodrigopavezi why is it important to know the service?

Re username: getting it from the same call as client ID and dumping it in the log makes the most sense to me.

**Comment by rodrigopavezi** [comment]
@alexey-rise I am thinking like that. If I am third party developer and I am going through my apps activities I guess it will help me to understand what my app is calling if I see that the call to a certain api is from some service. It would also help me when looking something on the documentation. 

If you don't it useful I can remove it. It is up to you guys @alexey-rise  @tejohnso @ByronDarlison.

Thanks

**Comment by alexey-rise** [comment]
@rodrigopavezi service is an internal entity the 3rd party developers shouldn't really care about. 
They shouldn't need to know that Storage API is provided by service A while Store API is provided by service B. 
They just need to know that their app is using these APIs and their status. Too much information leads to confusion. Do you follow?

**Comment by rodrigopavezi** [comment]
@alexey-rise yeap, I follow and I will remove it. cheers.

**Comment by rodrigopavezi** [comment]
@alexey-rise I have made the change. could you please review the last two commits? thanks

**Comment by rodrigopavezi** [comment]
@alexey-rise I have done some refactoring removing the unused code. please review. Thanks

**Comment by alexey-rise** [comment]
:+1:

**Pull request merged**
