### PR TITLE
Feature/integration test

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@alexey-rise I have implemented an integration test for the monitoring. So, for that I have used Gradle as it makes life easier for this purpose. It is now only checking if a log entry is created when a servlet is accessed. I was wondering if we could test the client id on the log message. For doing that I might try using the https://github.com/GoogleCloudPlatform/gradle-appengine-plugin.

Please review, let me know what you think. Note that I still have to added the client id to the httpServletRequest so api can use it. I will work on it tomorrow.

@tejohnso FYI.

Cheers.

### CODE REVIEW

**Comment by tejohnso** [comment]
I would suggest the use of Maven to be consistent with other projects.

**Comment by ByronDarlison** [comment]
@rodrigopavezi @tejohnso @alexey-rise can you take me through what Gradle is and how it relates to Maven, and if same, why we need to introduce another tool set? I would like to keep our tools to the smallest list possible so that we have the greatest chance of most people knowing them and therefore able to easily work cross teams. Let me know. Thanks

**Comment by tejohnso** [comment]
Gradle does the same project assembly/build job that Maven does.  Why we would need it here, I'm not sure.  It's apparently a more modern and flexible tool than maven but I don't know what specific benefit is being leveraged.

**Comment by rodrigopavezi** [comment]
@ByronDarlison Gradle is the latest and greatest build management tool for Java projects. It has been around since 2009 and has been stable for about 2 years. Why is it better than Maven and ant? It combines good parts of both Maven and ant. Maven is not great because it is XML based, thus, harder to write and maintain the scripts. Gradle is more flexible and allows to deal easily with complex tasks such as the case here, Integration Test. Just look the results of googling how to do integration test with Maven, then with Gradle. Gradle is much simpler, things works out of the box. I saved one day of work because I've chosen Gradle for this project.

Now I would like you to see what some of the Gurus of software development, such as Martin Fowler,  have to say about both tools. The company he works called Thought Works every year releases a Technology Radar that advises which tools tech companies should be working with. 

Here is what they say about Maven: http://www.thoughtworks.com/radar/tools/maven (Note that Hold means that companies should stop using it, they advise stop using Maven since 2012)

Here is what they say about Gradle: http://www.thoughtworks.com/radar/tools/gradle (Note that they advise to adopt Gradle since 2013).

So for me what drives me to use Gradle is that it is simpler than Maven, more flexible, have great plugins which do not need much configuration, they work out of the box. It also helps with complex tasks such as integration or e2e tests. Furthermore, I am using a tool that is on the edge of technology rather than following its tail. 

If I can make a comparison. For me using Maven is the same feeling when using pure JS+JQuery instead of using Angular. 

@tejohnso 
Just google how to do integration test with Maven and then with gradle. Compare both and you will see how simpler Gradle is, so making our life easier. I am lazy developer, I want to simplify things when I see that it is possible. Of course, always considering the trending. We cannot use a tool that nobody else uses, that is not the case with Gradle. Another comparison is Grunt vs. Gulp. Grunt is like Maven you have over-configuration of simple tasks. Gulp is more flexible. 

Please let me know if you didn't understand something. 

Cheers!!

**Comment by ByronDarlison** [comment]
@rodrigopavezi I understand your point, but, for all of the reasons I said we can't pick up tools and frameworks ad hoc as we will end up with an unsupportable mess if everyone used whatever they pleased. We have to weigh benefit of a tool, versus the cost to upgrade everyone to it, versus continuity of proficiency with the tools across the whole team. Ad hoc tool usage won't cut it. You follow me?

Which means, if we have a tool selected for a purpose, like Maven, we can't use another tool, like Gradle, unless everyone proactively, not after the fact, agrees that Gradle is where we are going. And given how far behind we are and everyone's pressing priorities I can't see making this switch unless  Gradle offers some very significant advantages. I would like you to work this through with @alexey-rise and @tejohnso and let me know the conclusion. And stop all further Gradle implementation until you have this conclusion reached, and please, keep this in mind for all future decisions. You must discuss decisions like this proactively. Understood?

Thanks

**Comment by rodrigopavezi** [comment]
@ByronDarlison understood. I just used it here because it simplifies the needs of the implementation of the integration tests for this project. Gradle is not that hard to learn as it follows the same principles as Maven and Ant so I thought it wouldn't have a high cost on maintaining the project even though you are new to Gradle. I agree with you we have to consider all the facts and get feedbacks from everyone before using a tool. So, @tejohnso @alexey-rise please let me know if you want me to change it to Maven. I can do it with no problem. I will just need some more time.

Cheers!!

**Comment by tejohnso** [comment]
Abandoning XML is nice.  I don't use maven for integration tests so I don't see a major advantage there.  I don't think it would take one day of work for that simple test using casperjs.  The integration test doesn't need to be build-in as part of the build tool's responsibilities.  See circle.yml in storage-server.

But we would have to verify the full functionality of the gradle appengine plugin before agreeing to use it for our projects.

**Comment by rodrigopavezi** [comment]
@tejohnso I would prefer keeping the integration tests in Java instead of using a different language if is doable in Java. If you add javascript there are more tools to maintain, npm install and bower install can fail the build as it is not as stable as Java. But I would definitely use this path if I can't do with Java or on a javascript project.

With regards  to verify Gradle google appengine plugin it is a case of having a project that implements it. It doesn't need to be all projects changed over night or even changed. It is just a case of moving forward. We can start with one project and verify if it works as we would like. If not, it was only one project.

Cheers!

**Comment by tejohnso** [comment]
@rodrigopavezi in this specific case you definitely don't need javascript since you're just hitting the servlet url and looking at the output of a file.  I would just use the app engine devserver and the command line to do the job.  But the point is that it's not a Gradle / Maven issue unless you make it a Gradle / Maven issue by forcing the build tool to run your integration tests.  That doesn't have to be the case, since you can run the integration test as part of your deployment process in circle.yml.

I'd have no problem moving away from Maven toward Gradle but the benefit isn't significant as far as  I can tell.  And we certainly don't want "only one project" using a different system from all the others unless that system has the potential to stand on its own and fully replace the other as CircleCI did Jenkins.

**Comment by rodrigopavezi** [comment]
@tejohnso I understand you. but I am just thinking like that. what is the most integrated with Java, self contained within the project way to run the integration tests? Looking in the perspective that this is a open source project where we should be pursuing to give our best to the community so they can just pull the project source code run a single command line and have it nice and clean. We can do integration test with minimal of automation, but I think we should be pursuing as much automation as possible so make it easy for the Continuous Deployment and the community. To do that so, we must have a tool that helps with automation as much as possible.  

I suggest we move on and stop to agree to disagree. :-) If you all @ByronDarlison @tejohnso and @alexey-rise agree. I will implement the integration tests with Maven or any other way you think is suitable.
Please let me know.

Thanks a mill!!

**Comment by tejohnso** [comment]
Good point about the community.

**Comment by ByronDarlison** [comment]
@rodrigopavezi @tejohnso @alexey-rise this is beyond me technically. You need to reach a conclusion and let me know. Thanks

**Comment by tejohnso** [comment]
@alexey-rise You've recently converted core over to maven.  What were your impressions of it, and do you think it would be worth switching to Gradle?

**Comment by rodrigopavezi** [comment]
@tejohnso @alexey-rise  Just to show the comparison I did to get to my conclusions. 

this is what needs to be done on Maven to run Integration Tests separated from the Unit Test.

https://github.com/pkainulainen/maven-examples/blob/master/integration-testing/pom.xml

This is what needs to be done with Gradle:
screen shot 2015-01-16 at 3 04 38 pm

**Comment by alexey-rise** [comment]
@rodrigopavezi @tejohnso @ByronDarlison my 5 cents: I am quite happy with Maven personally (I don't know why you guys hate XML so much :smile: ) and I haven't encountered any real "pain points" with it yet *and* given the amount of stuff I have in my backlog it doesn't make a lot of sense to me to switch to a different system right now.

Having said that, if everyone else decides that Gradle is the way I wouldn't mind learning something new.

**Comment by rodrigopavezi** [comment]
@tejohnso @alexey-rise if you guys are happy with Maven what do you thing if I implement this integration test with it? Cheers!

**Comment by tejohnso** [comment]
@rodrigopavezi I suggest you do not try to implement the integration test with maven if it's that complicated.  But we don't need to switch to gradle either.  If you want to hit a url as part of an integration test just start jetty then use curl.  

Switching to gradle should be a separate project.  I'd say there might be value in it, but it should be on the backlog along with all our other priorities.

**Comment by rodrigopavezi** [comment]
@tejohnso sure, agreed. Cheers!

**Pull request closed without merging**
